/// Integration tests for the `initialize` function and related admin helpers.
///
/// These tests exercise the public contract interface via
/// `CreatorEventManagerContractClient` (generated by `#[contractimpl]`).
use creator_event_manager::CreatorEventManagerContractClient;
use soroban_sdk::{testutils::Address as _, Address, Env};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Deploy a fresh contract and return (env, client, contract_id).
fn setup() -> (Env, CreatorEventManagerContractClient<'static>, Address) {
    let env = Env::default();
    let contract_id = env.register(creator_event_manager::CreatorEventManagerContract, ());
    let client = CreatorEventManagerContractClient::new(&env, &contract_id);
    // SAFETY: the Env outlives the test function; the 'static bound is
    // satisfied because we leak nothing outside the test.
    let client: CreatorEventManagerContractClient<'static> =
        unsafe { core::mem::transmute(client) };
    (env, client, contract_id)
}

/// Generate four distinct addresses that are all different from `contract_id`.
fn make_addresses(env: &Env) -> (Address, Address, Address, Address) {
    (
        Address::generate(env),
        Address::generate(env),
        Address::generate(env),
        Address::generate(env),
    )
}

// ---------------------------------------------------------------------------
// Happy-path tests
// ---------------------------------------------------------------------------

#[test]
fn test_initialize_succeeds() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);

    // Before initialization the contract should report not-initialized.
    assert!(!client.is_initialized());

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);

    assert!(client.is_initialized());
}

#[test]
fn test_initialize_stores_creation_fee() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    let fee = 5_000_000i128; // 0.5 XLM in stroops

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &fee);

    assert_eq!(client.get_creation_fee(), fee);
}

#[test]
fn test_initialize_contract_not_paused() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);

    assert!(!client.is_paused());
}

#[test]
fn test_is_initialized_false_before_init() {
    let (_env, client, _contract_id) = setup();
    assert!(!client.is_initialized());
}

#[test]
fn test_get_creation_fee_zero_before_init() {
    let (_env, client, _contract_id) = setup();
    // Before initialization the helper should return the default 0.
    assert_eq!(client.get_creation_fee(), 0i128);
}

// ---------------------------------------------------------------------------
// Re-initialization prevention
// ---------------------------------------------------------------------------

#[test]
#[should_panic(expected = "already_initialized")]
fn test_reinitialize_panics() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);

    // First call — must succeed.
    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);

    // Second call with different addresses — must panic.
    let (admin2, ai2, treasury2, xlm2) = make_addresses(&env);
    client.initialize(&admin2, &ai2, &treasury2, &xlm2, &2_000_000i128);
}

#[test]
#[should_panic(expected = "already_initialized")]
fn test_reinitialize_same_params_panics() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);
    // Calling again with identical params must also panic.
    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);
}

// ---------------------------------------------------------------------------
// Address validation
// ---------------------------------------------------------------------------

#[test]
#[should_panic(expected = "invalid_address")]
fn test_admin_is_contract_self_panics() {
    let (env, client, contract_id) = setup();
    let (_a, ai_agent, treasury, xlm_token) = make_addresses(&env);

    // Pass the contract's own address as admin — must be rejected.
    client.initialize(
        &contract_id,
        &ai_agent,
        &treasury,
        &xlm_token,
        &1_000_000i128,
    );
}

#[test]
#[should_panic(expected = "invalid_address")]
fn test_ai_agent_is_contract_self_panics() {
    let (env, client, contract_id) = setup();
    let (admin, _a, treasury, xlm_token) = make_addresses(&env);

    client.initialize(&admin, &contract_id, &treasury, &xlm_token, &1_000_000i128);
}

#[test]
#[should_panic(expected = "invalid_address")]
fn test_treasury_is_contract_self_panics() {
    let (env, client, contract_id) = setup();
    let (admin, ai_agent, _a, xlm_token) = make_addresses(&env);

    client.initialize(&admin, &ai_agent, &contract_id, &xlm_token, &1_000_000i128);
}

#[test]
#[should_panic(expected = "invalid_address")]
fn test_xlm_token_is_contract_self_panics() {
    let (env, client, contract_id) = setup();
    let (admin, ai_agent, treasury, _a) = make_addresses(&env);

    client.initialize(&admin, &ai_agent, &treasury, &contract_id, &1_000_000i128);
}

// ---------------------------------------------------------------------------
// Creation fee validation
// ---------------------------------------------------------------------------

#[test]
#[should_panic(expected = "invalid_creation_fee")]
fn test_zero_creation_fee_panics() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &0i128);
}

#[test]
#[should_panic(expected = "invalid_creation_fee")]
fn test_negative_creation_fee_panics() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &-1i128);
}

#[test]
fn test_minimum_positive_fee_accepted() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);

    // Fee of 1 stroop is the smallest valid value.
    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1i128);

    assert!(client.is_initialized());
    assert_eq!(client.get_creation_fee(), 1i128);
}

#[test]
fn test_large_creation_fee_accepted() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);

    // 100 XLM in stroops
    let fee = 1_000_000_000i128;
    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &fee);

    assert_eq!(client.get_creation_fee(), fee);
}

// ===========================================================================
// #787 — set_treasury
// ===========================================================================

#[test]
fn test_set_treasury_admin_can_update() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);

    let new_treasury = Address::generate(&env);
    client.set_treasury(&admin, &new_treasury);

    assert_eq!(client.get_treasury(), new_treasury);
}

#[test]
fn test_set_treasury_updates_storage_correctly() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);
    assert_eq!(client.get_treasury(), treasury);

    let new_treasury = Address::generate(&env);
    client.set_treasury(&admin, &new_treasury);
    assert_eq!(client.get_treasury(), new_treasury);

    // A second update also works
    let newest_treasury = Address::generate(&env);
    client.set_treasury(&admin, &newest_treasury);
    assert_eq!(client.get_treasury(), newest_treasury);
}

#[test]
#[should_panic(expected = "unauthorized")]
fn test_set_treasury_non_admin_is_rejected() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);

    let non_admin = Address::generate(&env);
    let new_treasury = Address::generate(&env);
    client.set_treasury(&non_admin, &new_treasury);
}

#[test]
#[should_panic(expected = "invalid_address")]
fn test_set_treasury_contract_self_is_rejected() {
    let (env, client, contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);
    client.set_treasury(&admin, &contract_id);
}

// ===========================================================================
// #788 — set_ai_agent
// ===========================================================================

#[test]
fn test_set_ai_agent_admin_can_update() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);

    let new_agent = Address::generate(&env);
    client.set_ai_agent(&admin, &new_agent);

    assert_eq!(client.get_ai_agent(), new_agent);
}

#[test]
fn test_set_ai_agent_updates_storage_correctly() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);
    assert_eq!(client.get_ai_agent(), ai_agent);

    let new_agent = Address::generate(&env);
    client.set_ai_agent(&admin, &new_agent);
    assert_eq!(client.get_ai_agent(), new_agent);
}

#[test]
#[should_panic(expected = "unauthorized")]
fn test_set_ai_agent_non_admin_is_rejected() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);

    let non_admin = Address::generate(&env);
    let new_agent = Address::generate(&env);
    client.set_ai_agent(&non_admin, &new_agent);
}

#[test]
#[should_panic(expected = "invalid_address")]
fn test_set_ai_agent_contract_self_is_rejected() {
    let (env, client, contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);
    client.set_ai_agent(&admin, &contract_id);
}

// ===========================================================================
// #789 — pause / unpause
// ===========================================================================

#[test]
fn test_admin_can_pause() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);
    assert!(!client.is_paused());

    client.pause(&admin);
    assert!(client.is_paused());
}

#[test]
fn test_admin_can_unpause() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);
    client.pause(&admin);
    assert!(client.is_paused());

    client.unpause(&admin);
    assert!(!client.is_paused());
}

#[test]
fn test_pause_unpause_cycle_repeatable() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);

    client.pause(&admin);
    assert!(client.is_paused());
    client.unpause(&admin);
    assert!(!client.is_paused());
    client.pause(&admin);
    assert!(client.is_paused());
    client.unpause(&admin);
    assert!(!client.is_paused());
}

#[test]
#[should_panic(expected = "unauthorized")]
fn test_non_admin_cannot_pause() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);

    let non_admin = Address::generate(&env);
    client.pause(&non_admin);
}

#[test]
#[should_panic(expected = "unauthorized")]
fn test_non_admin_cannot_unpause() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);
    client.pause(&admin);

    let non_admin = Address::generate(&env);
    client.unpause(&non_admin);
}

#[test]
#[should_panic(expected = "already_paused")]
fn test_cannot_pause_when_already_paused() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);
    client.pause(&admin);
    client.pause(&admin); // must panic
}

#[test]
#[should_panic(expected = "not_paused")]
fn test_cannot_unpause_when_not_paused() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);
    client.unpause(&admin); // must panic — contract is not paused
}

#[test]
#[should_panic(expected = "contract_paused")]
fn test_ensure_not_paused_blocks_when_paused() {
    let (env, client, contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);
    client.pause(&admin);

    // Storage is only accessible inside the contract context
    env.as_contract(&contract_id, || {
        creator_event_manager::admin::ensure_not_paused(&env);
    });
}

#[test]
fn test_ensure_not_paused_passes_when_active() {
    let (env, client, contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);

    // Should not panic — contract is active
    env.as_contract(&contract_id, || {
        creator_event_manager::admin::ensure_not_paused(&env);
    });
}

// ===========================================================================
// get_treasury / get_ai_agent read helpers
// ===========================================================================

#[test]
fn test_get_treasury_returns_initial_treasury() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);

    assert_eq!(client.get_treasury(), treasury);
}

#[test]
fn test_get_ai_agent_returns_initial_agent() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);

    assert_eq!(client.get_ai_agent(), ai_agent);
}

// ===========================================================================
// update_creation_fee tests
// ===========================================================================

#[test]
fn test_update_creation_fee_admin_can_update() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);
    assert_eq!(client.get_creation_fee(), 1_000_000i128);

    let new_fee = 2_000_000i128;
    client.update_creation_fee(&admin, &new_fee);

    assert_eq!(client.get_creation_fee(), new_fee);
}

#[test]
#[should_panic(expected = "unauthorized")]
fn test_update_creation_fee_non_admin_is_rejected() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);

    let non_admin = Address::generate(&env);
    let new_fee = 2_000_000i128;
    client.update_creation_fee(&non_admin, &new_fee);
}

#[test]
#[should_panic(expected = "invalid_creation_fee")]
fn test_update_creation_fee_must_be_strictly_positive() {
    let (env, client, _contract_id) = setup();
    let (admin, ai_agent, treasury, xlm_token) = make_addresses(&env);
    env.mock_all_auths();

    client.initialize(&admin, &ai_agent, &treasury, &xlm_token, &1_000_000i128);

    client.update_creation_fee(&admin, &0i128);
}

